# Generated by Django 5.1 on 2024-08-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companys_title', models.CharField(max_length=200)),
                ('companys_tel', models.IntegerField()),
                ('companys_url', models.URLField()),
                ('companys_address', models.CharField(max_length=300)),
                ('companys_describe', models.TextField()),
                ('total_headcount', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
