# Generated by Django 5.1 on 2024-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_alter_company_companys_tel_alter_company_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
