# Generated by Django 5.1.1 on 2024-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
