# Generated by Django 5.1.1 on 2024-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_company_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
