# Generated by Django 5.1.1 on 2024-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_latitude_company_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
