# Generated by Django 5.1 on 2024-09-03 03:01

import django.db.models.deletion
import lib.models.soft_delete
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Keelung', '基隆'), ('Taipei', '台北'), ('New Taipei', '新北'), ('Taoyuan', '桃園'), ('Hsinchu', '新竹'), ('Miaoli', '苗栗'), ('Taichung', '台中'), ('Changhua', '彰化'), ('Nantou', '南投'), ('Yunlin', '雲林'), ('Chiayi', '嘉義'), ('Tainan', '台南'), ('Kaohsiung', '高雄'), ('Pingtung', '屏東'), ('Taitung', '台東'), ('Hualien', '花蓮'), ('Yilan', '宜蘭'), ('Penghu', '澎湖'), ('Kinmen', '金門'), ('Lienchiang', '連江')], max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('contact_info', models.TextField()),
                ('salary_range', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('tenure', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'job_details',
            },
            bases=(lib.models.soft_delete.SoftDeletetable, models.Model),
        ),
        migrations.CreateModel(
            name='JobFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_favorite',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
