# Generated by Django 5.1 on 2024-09-04 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobfavorite',
            unique_together={('user', 'job')},
        ),
        migrations.AddField(
            model_name='job',
            name='favorite',
            field=models.ManyToManyField(through='jobs.JobFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='job',
            table='company_job',
        ),
        migrations.AlterModelTable(
            name='jobfavorite',
            table='favorite_job',
        ),
        migrations.RemoveField(
            model_name='jobfavorite',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
