# Generated by Django 5.1 on 2024-08-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='edit_at',
            new_name='updated_at_at',
        ),
    ]
