# Generated by Django 5.1.1 on 2024-09-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_table_jobfavorite_job_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="applied", max_length=20)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_resume",
                        to="jobs.job",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_job",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="resumes",
            field=models.ManyToManyField(
                through="jobs.Job_Resume", to="resumes.resume"
            ),
        ),
    ]
