# Generated by Django 5.1.1 on 2024-09-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_user'),
        ('jobs', '0002_alter_job_table_jobfavorite_job_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company'),
            preserve_default=False,
        ),
    ]
