# Generated by Django 5.1.1 on 2024-09-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_resume_job_resumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="companies.company",
            ),
            preserve_default=False,
        ),
    ]
