# Generated by Django 5.1.1 on 2024-09-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="skills",
        ),
    ]
