# Generated by Django 5.1.1 on 2024-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_tags_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
