# Generated by Django 5.1.1 on 2024-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
