# Generated by Django 5.1 on 2024-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
