# Generated by Django 5.1 on 2024-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userinfo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "user"), (2, "company")], default=1
            ),
        ),
    ]
