# Generated by Django 5.1 on 2024-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "user"), (2, "company")], null=True
            ),
        ),
    ]
