# Generated by Django 5.1.1 on 2024-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
