# Generated by Django 5.1 on 2024-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_alter_company_created_at_alter_company_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companys_tel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(max_length=15),
        ),
    ]
