# Generated by Django 5.1 on 2024-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(choices=[('Keelung', '基隆'), ('Taipei', '台北'), ('New Taipei', '新北'), ('Taoyuan', '桃園'), ('Hsinchu', '新竹'), ('Miaoli', '苗栗'), ('Taichung', '台中'), ('Changhua', '彰化'), ('Nantou', '南投'), ('Yunlin', '雲林'), ('Chiayi', '嘉義'), ('Tainan', '台南'), ('Kaohsiung', '高雄'), ('Pingtung', '屏東'), ('Taitung', '台東'), ('Hualien', '花蓮'), ('Yilan', '宜蘭'), ('Penghu', '澎湖'), ('Kinmen', '金門'), ('Lienchiang', '連江')], max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('jon_skills', models.TextField()),
                ('job_contact_info', models.TextField()),
                ('job_salary_range', models.TextField()),
                ('job_post_date', models.DateField(auto_now_add=True)),
                ('job_tenure', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'job_details',
            },
        ),
    ]
