LOCATION_CHOICES = [
    ("Keelung", "基隆"),
    ("Taipei", "台北"),
    ("New Taipei", "新北"),
    ("Taoyuan", "桃園"),
    ("Hsinchu", "新竹"),
    ("Miaoli", "苗栗"),
    ("Taichung", "台中"),
    ("Changhua", "彰化"),
    ("Nantou", "南投"),
    ("Yunlin", "雲林"),
    ("Chiayi", "嘉義"),
    ("Tainan", "台南"),
    ("Kaohsiung", "高雄"),
    ("Pingtung", "屏東"),
    ("Taitung", "台東"),
    ("Hualien", "花蓮"),
    ("Yilan", "宜蘭"),
    ("Penghu", "澎湖"),
    ("Kinmen", "金門"),
    ("Lienchiang", "連江"),
]
