# Generated by Django 5.1.1 on 2024-09-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
